[BXMSPROD-1945] Set empty next drools and product version
kiegroup/kie-ci pull request #1408
Opened 2023-01-17 17:51 UTC by lampajr

**Thank you for submitting this pull request**

**JIRA**: 

https://issues.redhat.com/browse/BXMSPROD-1945

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* referenced pull request 1
* referenced pull request 2
* referenced pull request 2
etc. 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

2023-01-18 17:23 UTC, mareknovotny approved these changes

2023-01-18 19:50 UTC, rgdoliveira approved these changes

2023-01-19 06:57 UTC, Ginxo requested changes
check my suggestions please

2023-01-19 06:57 UTC, Ginxo commented on job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
> +// def RHBOP_NEXT_PRODUCT_VERSION='8.30.0'
```suggestion
```

2023-01-19 06:57 UTC, Ginxo commented on job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
> +// def RHBOP_NEXT_DROOLS_VERSION='8.30.0'
```suggestion
```

2023-01-19 06:57 UTC, Ginxo commented on job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
> +
```suggestion
```

I would avoid this, I would expose instead
```
String rhbopNightlyStage(String branch, String configBranch, String version = '', String droolsVersion = '') {
```

2023-01-19 08:53 UTC, bacciotti approved these changes

2023-01-19 10:56 UTC, Ginxo approved these changes
LGTM

2023-01-19 10:56 UTC, merged