[KIECLOUD-683] - Find a way to retrieve the image name built os OSBS
kiegroup/kie-ci pull request #1435
Opened 2023-02-03 15:26 UTC by spolti

Signed-off-by: Spolti <fspolti@redhat.com>

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://examle.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* referenced pull request 1
* referenced pull request 2
* referenced pull request 2
etc. 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

2023-02-03 17:03 UTC, lampajr commented
It looks great to me.
Just a proposal, the script could be minimized a bit in order to avoid using python, e.g., something like this using `jq` (which should be already installed - is it?):

```
$(/usr/bin/brew call --json-output getTaskResult $( cat output.txt| grep -oP 'Task \\d{8}' | cut -d" " -f2) | jq -nre "input.repositories[0]")
```

In this way you can remove the python env activation - a bit lighter.

Note: `-ne` ensure that `jq` exits with non-zero code if empty input or if `null` result.

This is just a proposal, it does the same thing you did with python.. so up to you :)

2023-02-03 17:11 UTC, lampajr commented
My only concern is that, if `brew call` fails, the python script could be invoked with empty input making it failing but with 0-code exit status. Not 100% sure but something to double check.

2023-02-06 13:39 UTC, spolti commented
@lampajr updated, please take a look.

2023-02-06 14:22 UTC, lampajr requested changes
@spolti some suggestions, I think the proper way to export it is using:
`env.VARIABLE = "<VALUE>"`

2023-02-06 14:22 UTC, lampajr commented on job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
> +                                  env.BUILT_IMAGE: get_image_name.trim()
```suggestion
                                  env.BUILT_IMAGE = "${get_image_name.trim()}"
```

2023-02-06 14:22 UTC, lampajr commented on job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy
> +                                  env.BUILT_IMAGE: get_image_name.trim()
```suggestion
                                  env.BUILT_IMAGE = "${get_image_name.trim()}"
```

2023-02-06 14:22 UTC, lampajr commented on job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy
> +import hudson.EnvVars
```suggestion

```

2023-02-06 14:22 UTC, lampajr commented on job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy
> +import hudson.model.Environment
```suggestion

```

2023-02-06 14:23 UTC, lampajr commented on job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy
> +import hudson.EnvVars
I think this can be removed if using the `env.VARIABLE = "<VALUE>"` approach

2023-02-06 14:23 UTC, lampajr commented on job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy
> +import hudson.model.Environment
Same as before

2023-02-06 14:30 UTC, lampajr requested changes
sorry, found  a type (missing double quote)

2023-02-06 14:30 UTC, lampajr commented on job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
> +                                  RESULT=$(/usr/bin/brew call --json-output getTaskResult $( cat output.txt| grep -oP 'Task \\d{8}' | cut -d" " -f2) | jq -nre "input.repositories[0])
```suggestion
                                  RESULT=$(/usr/bin/brew call --json-output getTaskResult $( cat output.txt| grep -oP 'Task \\d{8}' | cut -d" " -f2) | jq -nre "input.repositories[0]")
```

2023-02-06 14:30 UTC, lampajr commented on job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy
> +                                  RESULT=$(/usr/bin/brew call --json-output getTaskResult $( cat output.txt| grep -oP 'Task \\d{8}' | cut -d" " -f2) |  jq -nre "input.repositories[0])
```suggestion
                                  RESULT=$(/usr/bin/brew call --json-output getTaskResult $( cat output.txt| grep -oP 'Task \\d{8}' | cut -d" " -f2) |  jq -nre "input.repositories[0]")
```

2023-02-07 08:34 UTC, lampajr approved these changes

2023-02-07 11:30 UTC, merged