[KIECLOUD-663] Create pipeline for rhpam-kogito operator
kiegroup/kie-ci pull request #1438
Opened 2023-02-09 15:28 UTC by desmax74

See:https://issues.redhat.com/browse/KIECLOUD-663
Signed-off-by: desmax74 <mdessi@redhat.com>

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://examle.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* referenced pull request 1
* referenced pull request 2
* referenced pull request 2
etc. 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

2023-02-09 15:28 UTC, desmax74 commented
@lampajr

2023-02-09 15:30 UTC, lampajr requested changes
I think even those lines can be safely removed
```
sh 'git config --global user.email $GIT_EMAIL'
sh 'git config --global user.name $GIT_AUTHOR'
```

2023-02-13 08:30 UTC, lampajr commented on job-dsls/jobs/osbs/operators_osbs_seed_cloud_jobs.groovy
> +                          checkout(githubscm.resolveRepository(operator_repo_name, GITHUB_ORG_UNIT, operator_branch, false))
Just as reminder, `GITHUB_ORG_UNIT` must be the repository owner e.g., `kiegroup`.

2023-02-13 08:30 UTC, lampajr approved these changes

2023-02-14 12:45 UTC, spolti approved these changes

2023-02-14 12:45 UTC, merged